# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

- task: Docker@2
  inputs:
    containerRegistry: 'docker hub'
    repository: 'jintekicorp/d2ebot'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'